//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.CaseConnectors = new HashSet<CaseConnector>();
            this.MotherBoardFormFactors = new HashSet<MotherBoardFormFactor>();
            this.FrontPanelMaterials = new HashSet<Material>();
            this.Materials = new HashSet<Material>();
        }
    
        public int IdComponent { get; set; }
        public int IdCaseSize { get; set; }
        public int IdPowerSupplyFormFactor { get; set; }
        public byte ExpansionSlotsQuantity { get; set; }
        public int MaxVideoCardLength { get; set; }
        public int MaxCoolerHeigth { get; set; }
        public bool LiquidCoolerCompatible { get; set; }
        public byte Storage35Quantity { get; set; }
        public byte Storage25Quantity { get; set; }
        public string MotherBoardOrientation { get; set; }
        public short Length { get; set; }
        public short Width { get; set; }
        public short Height { get; set; }
        public int IdMainColor { get; set; }
        public bool HasWindow { get; set; }
        public Nullable<int> IdLigthingType { get; set; }
        public string PowerSupplyOrientation { get; set; }
        public bool HasCardReader { get; set; }
    
        public virtual CaseSize CaseSize { get; set; }
        public virtual Color Color { get; set; }
        public virtual Component Component { get; set; }
        public virtual LightingType LightingType { get; set; }
        public virtual PowerSupplyFormFactor PowerSupplyFormFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseConnector> CaseConnectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotherBoardFormFactor> MotherBoardFormFactors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> FrontPanelMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Materials { get; set; }
    }
}
