//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual DataStorage DataStorage { get; set; }
        public virtual MotherBoard MotherBoard { get; set; }
        public virtual PowerSupply PowerSupply { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual ProcessorCooler ProcessorCooler { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual VideoCard VideoCard { get; set; }
    }
}
