//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfiguratorPCEntities : DbContext
    {
        public ConfiguratorPCEntities()
            : base("name=ConfiguratorPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<FormFactor> FormFactors { get; set; }
        public virtual DbSet<MemoryFormFactor> MemoryFormFactors { get; set; }
        public virtual DbSet<MemoryType> MemoryTypes { get; set; }
        public virtual DbSet<MotherBoard> MotherBoards { get; set; }
        public virtual DbSet<Processor> Processors { get; set; }
        public virtual DbSet<Socket> Sockets { get; set; }
    }
}
