//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cooler
    {
        public int IdProcessorCooler { get; set; }
        public short Heigth { get; set; }
        public string ConstructionType { get; set; }
        public int IdBaseMaterial { get; set; }
        public Nullable<byte> TermPipeQuantity { get; set; }
        public Nullable<byte> TermPipeDiameter { get; set; }
        public string NickelCoating { get; set; }
        public short Width { get; set; }
        public short Length { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual ProcessorCooler ProcessorCooler { get; set; }
    }
}
