//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDD
    {
        public int IdDataStorage { get; set; }
        public string FormFactor { get; set; }
        public short CacheSize { get; set; }
        public short RotationSpeed { get; set; }
        public string WriteTech { get; set; }
        public byte ActiveNoiseLevel { get; set; }
        public byte PassiveNoiseLevel { get; set; }
        public decimal PassiveEnergyUse { get; set; }
        public decimal MaxEnergyUse { get; set; }
        public byte MaxTemp { get; set; }
    
        public virtual DataStorage DataStorage { get; set; }
    }
}
