//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidCooler
    {
        public int IdProcessorCooler { get; set; }
        public bool Serviced { get; set; }
        public int IdWaterblockMaterial { get; set; }
        public string WaterblockSize { get; set; }
        public short RadiatorLength { get; set; }
        public short RadiatorWidth { get; set; }
        public short RadiatorThickness { get; set; }
        public short PumpRotationSpeed { get; set; }
        public string PumpConnector { get; set; }
        public short PipeLength { get; set; }
        public bool TransparentPipe { get; set; }
        public int IdRadiatorSize { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual ProcessorCooler ProcessorCooler { get; set; }
        public virtual RadiatorSize RadiatorSize { get; set; }
    }
}
