//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Processor()
        {
            this.RAMTypes = new HashSet<RAMType>();
        }
    
        public int IdComponent { get; set; }
        public int IdSocket { get; set; }
        public Nullable<int> IdGraphicsProcessingUnit { get; set; }
        public int IdCore { get; set; }
        public int MaxMemorySize { get; set; }
        public bool HasCooler { get; set; }
        public byte CoreQuantity { get; set; }
        public byte MaxThreadQuantity { get; set; }
        public byte ProductiveCoreQuantity { get; set; }
        public Nullable<byte> EnergyEfficientCoreQuantity { get; set; }
        public decimal CacheL2Size { get; set; }
        public Nullable<decimal> CacheL3Size { get; set; }
        public byte TechProcess { get; set; }
        public decimal BaseFrequency { get; set; }
        public Nullable<decimal> MaxFrequency { get; set; }
        public Nullable<decimal> BaseFrequencyEnergyEfficientCore { get; set; }
        public Nullable<decimal> MaxFrequencyEnergyEfficientCore { get; set; }
        public bool FreeMultiplier { get; set; }
        public short MaxRAMFrequency { get; set; }
        public bool HasECC { get; set; }
        public byte TDP { get; set; }
        public byte MaxTemperature { get; set; }
        public int IdPCIEController { get; set; }
        public byte PCIEQuantity { get; set; }
        public byte StreamRAMQuantity { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Core Core { get; set; }
        public virtual GraphicsProcessingUnit GraphicsProcessingUnit { get; set; }
        public virtual PCIEController PCIEController { get; set; }
        public virtual Socket Socket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAMType> RAMTypes { get; set; }
    }
}
