//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSD
    {
        public int IdDataStorage { get; set; }
        public string BitQuantityOnCell { get; set; }
        public string MemoryStructure { get; set; }
        public short MinSpeed { get; set; }
        public short MaxSpeed { get; set; }
        public byte TotalBytesWritten { get; set; }
        public decimal DWPD { get; set; }
    
        public virtual DataStorage DataStorage { get; set; }
        public virtual M2SSD M2SSD { get; set; }
    }
}
