//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoCardOutput
    {
        public int IdVideoCard { get; set; }
        public int IdVideoOutput { get; set; }
        public byte Quantity { get; set; }
    
        public virtual VideoCard VideoCard { get; set; }
        public virtual VideoOutput VideoOutput { get; set; }
    }
}
