//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorUploadImage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.MotherBoardFormFactors = new HashSet<MotherBoardFormFactor>();
        }
    
        public int IdComponent { get; set; }
        public int IdPowerSupplyFormFactor { get; set; }
        public byte ExpansionSlotsQuantity { get; set; }
        public int MaxVideoCardLength { get; set; }
        public int MaxCoolerHeigth { get; set; }
        public bool LiquidCoolerCompatible { get; set; }
        public byte Storage35Quantity { get; set; }
        public byte Storage25Quantity { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual PowerSupplyFormFactor PowerSupplyFormFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotherBoardFormFactor> MotherBoardFormFactors { get; set; }
    }
}
