//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorUploadImage
{
    using System;
    using System.Collections.Generic;
    
    public partial class M2SSD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M2SSD()
        {
            this.M2Key = new HashSet<M2Key>();
        }
    
        public int IdSSD { get; set; }
        public Nullable<int> IdFormFactor { get; set; }
    
        public virtual M2FormFactor M2FormFactor { get; set; }
        public virtual SSD SSD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M2Key> M2Key { get; set; }
    }
}
