//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorUploadImage
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherBoardM2Key
    {
        public int IdMotherBoard { get; set; }
        public int IdFormFactor { get; set; }
        public int IdKey { get; set; }
    
        public virtual M2FormFactor M2FormFactor { get; set; }
        public virtual M2Key M2Key { get; set; }
        public virtual MotherBoard MotherBoard { get; set; }
    }
}
