//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorUploadImage
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerSupply
    {
        public int IdComponent { get; set; }
        public int IdPowerSupplyFormFactor { get; set; }
        public short Power { get; set; }
        public byte VideoCardSupplyQuantity { get; set; }
        public byte ProcessorSupplyQuantity { get; set; }
        public byte SATASupplyQuantity { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual PowerSupplyFormFactor PowerSupplyFormFactor { get; set; }
    }
}
